### PR TITLE
Fix issue with bucket creation in us-east-1

### PR DESCRIPTION
**Pull request by Donohue**
Signed-off-by: Brian Donohue <briandonohue@pinterest.com>

### CODE REVIEW

**Comment by ooq** [comment]
@Donohue Thanks for the PR.
Can you provide some descriptions on the issue you are fixing here?

**Comment by ericmjonas** [comment]
Hey Brian thanks so much for the PR -- does us-east-1 have different bucket creation semantics? @ooq we should probably run our CI in multiple regions to make sure we don't have these bugs.

**Comment by Donohue** [comment]
Hey @ericmjonas and @ooq this ticket describes the issue in detail: https://github.com/boto/boto3/issues/125

Here's the relevant comment for convenience:
> This is an artifact of the underlying S3 API and the fact that it doesn't accept us-east-1. To create an S3 bucket in us-east-1 you can just not specify any CreateBucketConfiguration: s3.create_bucket(Bucket='foo').

There was an error creating the bucket in us-east-1 during setup and I verified that this resolves it.

**Comment by ooq** [comment]
@Donohue Indeed! I just tried and verified this as well.
I'm surprised that they haven't fixed it after all this time.

We'll merge your PR after fixing our Travis build. Thanks again.

**Comment by Donohue** [comment]
Cool 😎

**Pull request merged**
