### PR TITLE
Standalone bug-fixes

### LINKED ISSUE #189: Executor won't run from shard if numshards = 1

### PR DESCRIPTION
**Pull request by ericmjonas**
First, I want to open with this pull request is too large and is the result of developing off-master for too long. @Vaishaal and I were the main users of standalone and started doing our own thing. Lately, the drift has hurt us. Additionally, now there's too much publicly-pushed code to do a clean rebase.

In short, don't do what I did. 

On to the PR! 
- Fix logging both stdout and stderr on the cloudwatch agent -- before stderr wasn't being sent to cloudwatch
- stop doing an apt-get update/upgrade on the standalone instance when we boot it, as some images have very specific pinned kernel versions for CUDA stuff
- add spot instance support; a lot of this is taken from the flintrock support that I originally wrote; vaishaal and I have both used this very successfully
- Run when there is only a single shard. fixes #189 
- switch standalone runner from using python multiprocessing to python threads. This is actually 
far superior as 
    - closer to the actual lambda model (wrenhandler is invoked in-process)
    - it signfiicantly simplifies the log handling code with Watchtower, preventing the behavior @Vaishaal  was seeing in #197 
- migrate to properly processing the messages with SQS visibility timeout

Merging this is a pre-req for dealing with issues #185 and #153 and #139 and #135

### CODE REVIEW

**Comment by Vaishaal** [comment]
Can we add the bootup jitter to this PR?

**Comment by ericmjonas** [comment]
Do we have any reason to think 120s is a good number? That's a lot of jitter!

**Comment by Vaishaal** [comment]
Given that you are launching 200+ instances when this matters, it didn't seem like a lot to me. We could probably make it 60s?

**Comment by Vaishaal** [comment]
Other than that the rest of the changes look good to me!

**Comment by Vaishaal** [comment]
LGTM

**Pull request merged**
